version: '3'
volumes:
  redisvol:
services:
  web:
    build: .
    command: python app.py
    ports:
     - "3050:5000"
  redis:
    image: "redis:alpine"
    volumes:
       - redisvol:/data    
    logging:
      driver: "awslogs"
      options:
         awslogs-region: "us-east-1"
         awslogs-group: "test"
         awslogs-stream: "flaskapp"
